name: test

on:
  push:
    branches:
      - "*"
    tags-ignore:
      - "v*"
  pull_request:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14, 16, 18, 20]
    name: node-${{ matrix.node-version }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "yarn"

      - run: yarn install --frozen-lockfile
      - run: yarn format-check
      - run: yarn test-cov
      - run: yarn build
